inducer/grudge

- test/test_grudge.py
Intended to fix [this failure](https://github.com/inducer/grudge/runs/859296484).
> Bump tolerances in test_mass_mat_trig to pass Github CI

- examples/wave/wave-eager-mpi.py
- examples/wave/wave-eager-var-velocity.py
- examples/wave/wave-eager.py
Sorry, I kept forgetting about this. 🙂 
I ran each example before and after the changes, and the results seem to be as expected (i.e., still stable, `u` unchanged, `v` different by a minus sign).
> Fix wave-eager* example signs

- grudge/execution.py
- test/test_grudge.py
Scalar case wasn't handled correctly because `np.bool` is not an `np.number`.
> Fix `map_if` handling of scalar conditions

- grudge/symbolic/dofdesc_inference.py
- grudge/symbolic/operators.py
- test/test_grudge.py
Seemed to think `pymbolic.Max` worked on pairs instead of just one iterator.
> Fix max norm handling

- grudge/eager.py
Fixes scalar case (previously missing "else" condition").
Tested in illinois-ceesd/mirgecom#128
> Fix object array vectorization in interior_trace_pair

- test/test_grudge.py
- test/test_mpi_communication.py
Separate PR for unrelated changes in #35
> Use actx_factory in all tests

- grudge/discretization.py
- grudge/eager.py
- grudge/symbolic/operators.py
Adds a `mass()` operator method to `EagerDGDiscretization` (and fixes a couple of little bugs).
> Add mass operator to EagerDGDiscretization

- .test-conda-env-py3.yml
To fix MPI/pocl hwloc conflicts like https://github.com/inducer/grudge/runs/1781132172?check_suite_focus=true.
cc @majosm
> Remove hwloc=1 version constraint in .test-conda-env-py3.yml

- grudge/eager.py
Tested in illinois-ceesd/mirgecom#180.
Seems to work, though it's maybe a little bit crude. It bypasses some of the from/to compatibility checks in `connection_from_dds`; I could implement this inside `connection_from_dds` instead, but I think then I would need to define a new connection type to return?
> Handle projection of constants

- .github/workflows/ci.yml
> test downstream projects

- examples/advection/surface.py
- examples/advection/var-velocity.py
- examples/advection/weak.py
- examples/dagrt-fusion.py
- examples/geometry.py
- examples/maxwell/cavities.py
- examples/wave/var-propagation-speed.py
- examples/wave/wave-min-mpi.py
- examples/wave/wave-min.py
- examples/wave/wave-op-mpi.py
- examples/wave/wave-op-var-velocity.py
- examples/wave/wave-op.py
- grudge/__init__.py
- grudge/discretization.py
- grudge/eager.py
- grudge/execution.py
- grudge/op.py
- grudge/shortcuts.py
- grudge/symbolic/mappers/__init__.py
- test/test_grudge.py
- test/test_mpi_communication.py
- unported-examples/benchmark_grudge/benchmark_mpi.py
- Before you ask: This branch should still run all of mirgecom unmodified. (see the CI)
- See [here](https://github.com/inducer/grudge/commit/7197ad3762fb14241e87eea11d8058d09c244c5f#diff-744059a765032fbe81a80c99e9263537af9cce120787d5d3944cd9e12fdf5528) for the changes in `wave-eager.py` (now `wave-op.`py`) that would be involved.
- Most changes are of the type `discr.inverse_mass(...)` -> `op.inverse_mass(discr, ...)`.
- Why? `grudge.eager`doesn't make a great deal of sense for what will become *the* interface for grudge (once the current symbolic `sym`/`bind` stuff under the hood goes away). Likewise for `EagerDGDiscretization`. That class name doesn't make much sense when it is used to drive computations with the lazy array context.
- Functions make more sense than methods for most …
> Deprecate grudge.eager in favor of grudge.op

- grudge/op.py
Upon detection of an object array *vec* input to `cross_rank_trace_pairs`, flatten the input array in order to use the existing infrastructure to communicate the data without modification, then recover the original shape upon formation of the returned TracePairs.
The current implementation "works" for _MIRGE-Com_'s purpose of communicating the 2D array of grad(Q) naturally via a call to `cross_rank_trace_pairs` in [NS PR](https://github.com/illinois-ceesd/mirgecom/pull/298).
> Enable comm of 2d arrays in cross_rank_pairs

- examples/advection/var-velocity.py
- examples/dagrt-fusion.py
- examples/geometry.py
- examples/maxwell/cavities.py
- examples/wave/var-propagation-speed.py
- examples/wave/wave-min-mpi.py
- examples/wave/wave-min.py
- examples/wave/wave-op-mpi.py
- examples/wave/wave-op-var-velocity.py
- examples/wave/wave-op.py
- test/mesh_data.py
- test/test_grudge.py
- test/test_mpi_communication.py
Depends on inducer/meshmode#133.
> Remove usage of deprecated n parameter in generate_*_rect_mesh

- grudge/execution.py
- grudge/symbolic/primitives.py
Together with that, it saves storing ~4 big DOF vectors on the GPU.
This goes towards https://github.com/inducer/grudge/issues/65.
cc @nchristensen
> Do not cache interior nodes

- grudge/op.py
- test/test_grudge.py
Noticed this last night when playing with #108. The Maxwell cavities example was returning complex-valued norms, which seemed odd... :)
cc @thomasgibson
> Fix, test complex norms

- doc/operators.rst
- examples/advection/surface.py
- examples/advection/var-velocity.py
- examples/advection/weak.py
- examples/geometry.py
- examples/maxwell/cavities.py
- examples/wave/var-propagation-speed.py
- examples/wave/wave-min-mpi.py
- examples/wave/wave-min.py
- examples/wave/wave-op-mpi.py
- examples/wave/wave-op-var-velocity.py
- examples/wave/wave-op.py
- grudge/dt_utils.py
- grudge/interpolation.py
- grudge/models/advection.py
- grudge/models/em.py
- grudge/models/wave.py
- grudge/op.py
- grudge/projection.py
- grudge/reductions.py
- grudge/trace_pair.py
- test/test_grudge.py
- test/test_mpi_communication.py
- test/test_op.py
Requires/Targets #108 because of the `dt_utils` module. This PR cuts down the content in `grudge.op` and modularizes the projection/interpolation and the reductions.
This also removes `op.nodes`/`op.normal`. The reason for this is due to the discussion here: https://github.com/illinois-ceesd/mirgecom/pull/360#discussion_r638097941. Overall, I pretty much agree that it makes much more sense to keep `nodes`/`normal` with the discretization collection. Furthermore, we should not need to deprecate since Mirgecom (our only direct dependency) has yet to adopt the post-eager interface. So we have a unique opportunity here to make some decisions that won't cause widespread breakage.
It also semi-revives `interp` in anticipate of addressing issue https://github.com/inducer/grudge/issues/38 in a …
> Grudge Refactoring

- grudge/models/em.py
:tada: 
https://github.com/inducer/arraycontext/pull/22/ found some more array context mistakes. Already worth it. [Relevant CI log](https://github.com/inducer/meshmode/runs/2799732706?check_suite_focus=true)
cc @thomasgibson
> Fix some array context abuse in the MaxwellOperator

- grudge/op.py
- grudge/reductions.py
- test/test_reductions.py
Allows nodal reductions to accept object arrays, and adds a couple new elementwise reductions. This PR also adds targeted unit tests for these reductions.
> Elementwise min/max and nodal reductions

- test/test_grudge_sym_old.py
Example CI failure (observed on 9f587ca):
https://github.com/inducer/arraycontext/pull/29/checks?check_run_id=2853420098
```
=================================== FAILURES ===================================
_ test_mass_mat_trig[<array context factory for <pyopencl.Device 'pthread-Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz' on 'Portable Computing Language'>-DISCR_TAG_BASE-3] _
[gw1] linux -- Python 3.9.4 /home/runner/work/arraycontext/arraycontext/grudge/.miniforge3/envs/testing/bin/python3
Traceback (most recent call last):
File "/home/runner/work/arraycontext/arraycontext/grudge/test/test_grudge_sym_old.py", line 150, in test_mass_mat_trig
assert err_2 < 1.0e-9, err_2
AssertionError: 1.6880221664905548e-09
assert 1.6880221664905548e-09 < 1e-09
_ test_mass_mat_trig[<array context factory …
```
> Bump tol test mass_mat_trig (symbolic tests)

- doc/utils.rst
- examples/advection/surface.py
- examples/advection/var-velocity.py
- examples/advection/weak.py
- examples/geometry.py
- examples/maxwell/cavities.py
- examples/wave/var-propagation-speed.py
- examples/wave/wave-min-mpi.py
- examples/wave/wave-op-mpi.py
- examples/wave/wave-op-var-velocity.py
- grudge/array_context.py
- grudge/dt_utils.py
- grudge/models/wave.py
- grudge/op.py
- grudge/reductions.py
- test/test_dt_utils.py
- test/test_grudge.py
- test/test_grudge_sym_old.py
- test/test_modal_connections.py
- test/test_mpi_communication.py
- test/test_op.py
- test/test_reductions.py
- test/test_trace_pair.py
- Force device scalars in tests and examples
- Use meshmode transform metadata
- Give grudge its own array context, use it
@alexfikl, could you take a quick look once the tests pass?
> Refactor to track meshmode array context changes

- grudge/symbolic/compiler.py
For https://github.com/inducer/loopy/pull/451
> Symbolic compiler: explicitly label input args

- grudge/geometry/__init__.py
- grudge/geometry/metrics.py
- grudge/op.py
Still to do:
cc @kaushikcfd 
Closes #144.
> More data reuse in differentiation

- grudge/discretization.py
- grudge/geometry/__init__.py
- grudge/geometry/metrics.py
- grudge/op.py
This defines a connection from the default nodal discretization to a P^0 (pw constant) discretization, to which all constant-per-element geometry terms (geometry derivatives on simplices) are interpolated. That results in `DOFArray`s with group arrays of shape `(nelements, 1)`, which, happily, broadcast cleanly over `(nelements, nunit_dofs)` with exactly the desired semantics. The other PRs have already wired up the infrastructure bits to make this go.
Needs (all merged):
- https://github.com/inducer/modepy/pull/42
- https://github.com/inducer/arraycontext/pull/85
- https://github.com/inducer/arraycontext/pull/86
- https://github.com/illinois-ceesd/mirgecom/pull/505
> P0 geometry

- examples/advection/var-velocity.py
Run with
```
pycl var-velocity.py --visualize --flux=central
```
to see the instability. Run with
```
pycl var-velocity.py --visualize --flux=central --use-quad
```
to see how overintegration adresses the issue. In this example, it seems that upwinding has enough dissipation to overwhelm the instability and stabilize the method.
cc @MTCam
> Tweak var velocity advection demo to show aliasing instability

- grudge/op.py
- grudge/reductions.py
- test/test_grudge.py
~~:warning: Depends on inducer/arraycontext#112 (for correct `np.ndarray` handling in `_map_array_container_impl`). :warning:~~ (Merged.)
Avoids some unnecessary squaring/`sqrt`ing, ~~and also handles the "object array of scalars" case without resorting to a duplicate implementation ([previous discussion](https://github.com/inducer/grudge/pull/154#discussion_r733164776)).~~
~~Not entirely sure whether what I'm doing for the scalar case in `_apply_mass_operator` is legit, but it at least replicates the previous behavior.~~ (Ended up removing support for norms of scalars.)
> Reimplement `norm()` without recursion

- grudge/symbolic/dofdesc_inference.py
Needed for https://github.com/inducer/pymbolic/pull/75.
> Add missing map_common_subexpression_uncached to DOFDescInferenceMapper

- grudge/trace_pair.py
This simple PR removes the deprecation warning for `interior_trace_pair`, since there are legitimate reasons (cc. @MTCam and the Navier-Stokes operator) you'd want to handle the rank-local interior trace pairs independently from the cross-rank pairs.
Also we may want to try some latency hiding in lazy mode soon, so we probably want to treat all rank-local surface + volume terms as a unit when attempting to overlap communication with computation.
> Do not deprecate rank-local interior trace pairs

- examples/wave/wave-op-mpi.py
- grudge/op.py
- grudge/projection.py
- grudge/reductions.py
- grudge/trace_pair.py
- test/test_mpi_communication.py
- test/test_reductions.py
This PR modifies existing grudge routines to work on arbitrary array containers and batches eager MPI communication of containers.
~Requires: https://github.com/inducer/arraycontext/pull/91~
> Array container support and batched (eager) communication

- grudge/op.py
I accidentally missed this when reviewing #191 --- sorry!
> Patch for `_div_helper`: pass dof descriptor when mapping containers

- test/mesh_data.py
- test/test_grudge.py
The test started failing with v4.9 and I couldn't find a set of "CharacteristicLengthMax" that would make it cleanly pass on v4.9 and v4.8. 
This modifies it to just use `generate_sphere` with `affine_map` to make a spheroid. The test seems to pass nicely now.
> Fix test_surface_divergence_theorem with gmsh v4.9

- grudge/dt_utils.py
- grudge/reductions.py
- test/test_dt_utils.py
This PR fixes #184
The logic here is that it's safe to force the elementwise reductions to have a shape of `(nelem, 1)` by definition of a reduction in this context; no need to broadcast to a full DOFArray
> Force a single-value per element for elementwise reductions

- grudge/trace_pair.py
It is OK to use COMM_WORLD here, and this continues to work even for array contexts that don't have the mpi_communicator attribute.  This fixes many failing tests in MIRGE-Com.
> Get_attr from world

- grudge/dt_utils.py
I noticed `characteristic_lengthscales` was returning larger values than expected for 1D (e.g., returning `2` for a cell of length `1` with 1st order), and this appears to be the culprit. `dt_geometric_factors` returns inscribed circle radii for `dim > 1`, but it returns diameters for `dim == 1`.
> Make the result of `dt_geometric_factors` in 1D consistent with other dimensions

- .github/workflows/ci.yml
https://github.com/inducer/grudge/runs/5400939277?check_suite_focus=true showed this failure:
```
--------------------------------------------------------------------------
There are not enough slots available in the system to satisfy the 2
slots that were requested by the application:
python
Either request fewer slots for your application, or make more slots
available for use.
A "slot" is the Open MPI term for an allocatable unit where we can
launch a process.  The number of slots available are defined by the
environment in which Open MPI processes are run:
1. Hostfile, via "slots=N" clauses (N defaults to number of
processor cores if not provided)
2. The --host command line parameter, via a ":N" suffix on the
hostname (N defaults to 1 if not provided)
3. Resource manager (e.g., SLURM, …
```
> Oversubscribe MPI example run

- .github/workflows/ci.yml
cc: @MTCam 
Could help with catching https://github.com/illinois-ceesd/mirgecom/issues/617
cc: #222
> test mirgecom examples in CI

- test/test_grudge_sym_old.py
For this failure:
```
=================================== FAILURES ===================================
_ test_mass_mat_trig[<PyOpenCLArrayContext for <pyopencl.Device 'pthread-Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz' on 'Portable Computing Language'>>-DISCR_TAG_BASE-3] _
[gw3] linux -- Python 3.10.4 /home/runner/work/meshmode/meshmode/grudge/.miniforge3/envs/testing/bin/python3
Traceback (most recent call last):
File "/home/runner/work/meshmode/meshmode/grudge/test/test_grudge_sym_old.py", line 147, in test_mass_mat_trig
assert err_1 < 2e-9, err_1
AssertionError: 5.609763320535421e-09
assert 5.609763320535421e-09 < 2e-09
_ test_mass_mat_trig[<PyOpenCLArrayContext for <pyopencl.Device 'pthread-Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz' on 'Portable Computing …
```
> Bump a tolerance in test_mass_mat_trig (old symbolic tests)

- test/test_grudge_sym_old.py
Sample failure: https://github.com/inducer/loopy/runs/6051602991?check_suite_focus=true
```
=================================== FAILURES ===================================
_ test_mass_mat_trig[<PyOpenCLArrayContext for <pyopencl.Device 'pthread-Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz' on 'Portable Computing Language'>>-DISCR_TAG_BASE-3] _
[gw3] linux -- Python 3.10.4 /home/runner/work/loopy/loopy/grudge/.miniforge3/envs/testing/bin/python3
Traceback (most recent call last):
File "/home/runner/work/loopy/loopy/grudge/test/test_grudge_sym_old.py", line 151, in test_mass_mat_trig
assert err_2 < 2e-9, err_2
AssertionError: 4.918547347187996e-09
assert 4.918547347187996e-09 < 2e-09
_ test_mass_mat_trig[<PyOpenCLArrayContext for <pyopencl.Device 'pthread-Intel(R) Xeon(R) Platinum 8370C …
```
> Bump another tolerance in test_mass_mat_trig in sym old tests

- examples/wave/wave-op-mpi.py
- grudge/shortcuts.py
- test/test_grudge.py
This seems to work, and it seems to help a fair bit for the wave operator. It's at 0.008s on my laptop. (Earlier measurements were 0.06s, but I forgot what those were.)
Draft because:
cc @MTCam
> Add a helper to enable use of compiled LSRK45

- grudge/dt_utils.py
- grudge/op.py
- test/test_dt_utils.py
~~:warning: Depends on inducer/meshmode#330. :warning:~~ (Merged.)
> Make `dt_geometric_factors` work with empty meshes

- examples/advection/surface.py
- examples/advection/var-velocity.py
- examples/advection/weak.py
- examples/euler/acoustic_pulse.py
- examples/euler/vortex.py
- examples/geometry.py
- examples/hello-grudge.py
- examples/maxwell/cavities.py
- examples/wave/var-propagation-speed.py
- examples/wave/wave-min-mpi.py
- examples/wave/wave-op-mpi.py
- examples/wave/wave-op-var-velocity.py
- grudge/array_context.py
- grudge/discretization.py
- grudge/dt_utils.py
- grudge/geometry/metrics.py
- grudge/models/advection.py
- grudge/models/em.py
- grudge/models/euler.py
- grudge/models/wave.py
- grudge/op.py
- grudge/reductions.py
- grudge/trace_pair.py
- test/test_dt_utils.py
- test/test_euler_model.py
- test/test_grudge.py
- test/test_modal_connections.py
- test/test_mpi_communication.py
- test/test_op.py
- test/test_reductions.py
This takes #188 (in the form of https://github.com/kaushikcfd/grudge/commit/3d184d5e6886574cce2fb596e84091272d92a60e) and modernizes it for the merged form of https://github.com/inducer/meshmode/pull/284, and adds two commits to help avoid things that are now deprecated. This also includes https://github.com/kaushikcfd/grudge/commit/1d89eb28637ee89b6d3722d43639e029fa546d1e, because why not.
Empirically, with [this hacked version](https://github.com/inducer/meshmode/compare/kaushik-hacked) of https://github.com/kaushikcfd/meshmode/commits/main, it is still capable of transforming mirgecom code.
Best read commit-by-commit.
> Tag axes of discretization-related arrays

- grudge/projection.py
Since array containers stay together longer, this may help with generating sensible names. It's also entirely unnecessary to pick containers apart at this stage.
> Pass array containers to connection in `project()`

- grudge/array_context.py
Necessitated by https://github.com/inducer/pyopencl/pull/452/.
> Fix allocator type annotations in grudge.actx

- .pylintrc-local.yml
- doc/conf.py
- examples/hello-grudge.py
- grudge/__init__.py
- grudge/discretization.py
- grudge/dof_desc.py
- grudge/dt_utils.py
- grudge/eager.py
- grudge/geometry/metrics.py
- grudge/models/advection.py
- grudge/op.py
- grudge/projection.py
- grudge/reductions.py
- grudge/shortcuts.py
- grudge/trace_pair.py
- test/test_grudge.py
- test/test_mpi_communication.py
- test/test_reductions.py
Adds the subset of changes from #236, #239, #243, and #246 needed to support multiple non-interacting volume discretizations in a discretization collection. Notably, this PR includes all of the interface changes needed to make illinois-ceesd/mirgecom#726 mergeable.
> Multiple independent volumes

- grudge/array_context.py
Draft because:
cc @matthiasdiener
> Pytato+distributed: verify partition if in debug mode

- grudge/dt_utils.py
After doing this the `models.wave` can be digested by [BatchedEinsumArrayContext](https://github.com/inducer/arraycontext/pull/217) without falling back.
> Attach axes tags to cell volume terms in dt_geometric_factors

- examples/wave/wave-min-mpi.py
- examples/wave/wave-op-mpi.py
- test/test_mpi_communication.py
- cf. https://github.com/inducer/meshmode/pull/342.
- goes with (but doesn't require) https://github.com/inducer/meshmode/pull/376.
> Use `comm.scatter` for mesh distribution

- grudge/reductions.py
This is part of what was causing the fallback warnings in the Y3 production case.
> Add axis tags for reshape in `_apply_elementwise_reduction`

- .test-conda-env-py3.yml
Conda started finding solutions with pocl 1.3 for reasons I wasn't able to discover.
e.g. https://github.com/inducer/meshmode/actions/runs/6211644674/job/16861042998?pr=388
> Require pocl>=3.1 for improved SVM support

- .github/workflows/ci.yml
- grudge/discretization.py
- grudge/trace_pair.py
- test/test_modal_connections.py
- test/test_op.py
> `test_gradient`: test warped mesh, overintegration

- grudge/discretization.py
Missed this when working on inducer/meshmode#396.
> discretization: use part_id instead of removed part_nr

- grudge/projection.py
Handled in meshmode as of https://github.com/inducer/meshmode/pull/398, so no longer needed here.
> Remove redundant constant handling in `project()`

- examples/advection/surface.py
- examples/advection/var-velocity.py
- examples/advection/weak.py
The changes to `DOFArray` in https://github.com/inducer/meshmode/pull/421 seem to have slightly broken this example: when doing `dt * rhs`, dt was a `np.array(1.0)` and rhs was `DOFArray` and it wouldn't broadcast that anymore.
> Fix surface advection example

- grudge/array_context.py
Instances of `PyOpenCLArrayContext` that don't explicitly pass `force_device_scalars=True` will have it set to `False`. This is deprecated, and will be an error once inducer/arraycontext#278 goes in.
After the arraycontext PR gets merged I'll submit a follow-up here that makes the interface for `force_device_scalars` match (i.e., allow it to be `None`), so that it will only emit deprecation warnings when explicitly specified.
> Enable `force_device_scalars` by default

- grudge/reductions.py
- grudge/trace_pair.py
`dcoll.mpi_communicator` is deprecated.
Note: Can't remove `dcoll.mpi_communicator` yet, because https://github.com/inducer/grudge/pull/285 still needs it.
> Get MPI communicator from array context instead of `dcoll`

- .github/workflows/ci.yml
- examples/wave/wave-op-mpi.py
- grudge/array_context.py
- test/test_dt_utils.py
- test/test_metrics.py
> Add MPINumpyArrayContext

- test/mesh_data.py
The builder only uses the dim argument passed to it when generating the mesh despite having an attribute for default mesh resolutions to use.
An example where this builder is used is in `test_grudge.test_mass_operator_inverse`: https://github.com/inducer/grudge/blob/cc954d0cef476187ab478522a4d091a2fb3ec804/test/test_grudge.py#L250-L251
https://github.com/inducer/grudge/blob/cc954d0cef476187ab478522a4d091a2fb3ec804/test/test_grudge.py#L276-L277
Default resolutions for the builder are here: https://github.com/inducer/grudge/blob/cc954d0cef476187ab478522a4d091a2fb3ec804/test/mesh_data.py#L142-L150. 
Convergence tests aren't done for the inverse mass test in main (or else it would likely fail). Still, not using arguments seems to be unintended.
This PR changes the builder to use the arguments …
> Use arguments in `WarpedRectMeshBuilder` when generating the mesh

- doc/misc.rst
- doc/references.rst
This updates for formatting in `references.rst` a bit (mostly inspired by typos complaining about "SIAM J Sci Comput") and fixes some out of date URLs.
> Update references in docs

- examples/euler/acoustic_pulse.py
- examples/euler/vortex.py
- examples/wave/wave-op-mpi.py
- grudge/shortcuts.py
- test/test_mpi_communication.py
Made necessary by https://github.com/inducer/arraycontext/pull/305, see https://github.com/inducer/arraycontext/pull/305#issuecomment-2759225212.
Needs:
> Stop passing unevaluated args to actx.compiled functions
