examples/wave/wave-eager-mpi.py, examples/wave/wave-eager.py, grudge/eager.py
Includes #8. Do not merge before that.
=> Eager norm support obj array

grudge/eager.py, grudge/symbolic/primitives.py
=> Eager norm improvements

grudge/execution.py
=> Reinstate https://github.com/inducer/grudge/pull/19

grudge/eager.py, grudge/symbolic/primitives.py
Add some simple doc for unit normal getter.
=> Doc unit normal

grudge/execution.py
@nchristensen This gets rid of the diff kernel as it currently exists. This is needed in order to get lazy eval to go. Are you OK with this going into master? (I ask because you've been working with the diff kernel as it currently exists. The point is that this current version essentially does one limited form of fusion "prematurely", when creating this form is likely better left to the transformed side of things. I imagine that essentially the same kernel would reemerge post-fusion on the "other side".)
cc @matthiasdiener @kaushikcfd
=> Make reference diff use elwise_linear loopy kernel

grudge/symbolic/operators.py
=> Fix stringifier dispatch for Operator subclasses

grudge/execution.py, test/test_grudge.py
=> Fix normals for empty boundary

test/test_grudge.py
Fix some fallout from inducer/meshmode#135. 
Not sure why it didn't fail already in that PR, but it's failing now in inducer/meshmode#136 :(
=> Fix possible nan eoc in test_mass_surface_area

grudge/eager.py
Needed for illinois-ceesd/mirgecom#297.
=> Handle constant values in interior_trace_pair and cross_rank_trace_pairs

.github/workflows/ci.yml
=> Run flake8 in Github CI on target Py version

doc/discretization.rst, doc/misc.rst, grudge/eager.py
Cleans up unexpected fall-out from #67.
=> Re-document EagerDGDiscretization to avoid breaking mirgecom doc build

.github/workflows/ci.yml, .gitlab-ci.yml, .pylintrc-local.yml, examples/dagrt-fusion.py, grudge/discretization.py, grudge/eager.py, grudge/models/__init__.py, grudge/models/em.py, grudge/models/gas_dynamics/__init__.py, grudge/models/wave.py, grudge/op.py, grudge/symbolic/mappers/__init__.py, grudge/symbolic/operators.py, grudge/symbolic/tools.py, test/mesh_data.py, test/test_grudge.py
Found some more small typos, so went ahead and threw pylint at it and fixed them. Gitlab CI is running at
https://gitlab.tiker.net/fikl2/grudge/-/pipelines/154607
There's a big chunk in `models` that's ignored, but those don't seem to be up to date anyway.
=> Add pylint

grudge/symbolic/primitives.py
=> Do not cache the pseudoscalar in the discretization

examples/advection/surface.py, examples/advection/var-velocity.py, examples/advection/weak.py, examples/geometry.py, examples/maxwell/cavities.py, examples/wave/var-propagation-speed.py, examples/wave/wave-min-mpi.py, examples/wave/wave-min.py, examples/wave/wave-op-mpi.py, examples/wave/wave-op-var-velocity.py, examples/wave/wave-op.py, grudge/shortcuts.py
Towards https://github.com/inducer/grudge/issues/65.
cc @nchristensen
=> Default vis_order to None in make_visualizer shortcut

examples/advection/surface.py, examples/advection/var-velocity.py, examples/wave/wave-op-var-velocity.py, grudge/discretization.py, grudge/dof_desc.py, grudge/execution.py, grudge/models/advection.py, grudge/op.py, grudge/symbolic/dofdesc_inference.py, grudge/symbolic/mappers/__init__.py, grudge/symbolic/operators.py, grudge/symbolic/primitives.py, test/test_grudge.py, test/test_modal_connections.py
Drops `QTAG_` in favor of `DISCR_TAG_`
cc @majosm @alexfikl @inducer 
Closes #79.
=> Introduce discretization tags in place of quadrature tags

doc/conf.py, doc/misc.rst, requirements.txt, setup.py
This isn't technically needed yet (`arraycontext` is nothing but an empty shell for now), but it'll help me with some [upstream PR headaches](https://github.com/inducer/meshmode/pull/181).
=> Add arraycontext dep

examples/wave/wave-op-var-velocity.py, grudge/op.py, test/test_op.py
Open question: should these return an array of arrays or a 2D array?
=> Vectorize local_grad and weak_local_grad

grudge/discretization.py, grudge/eager.py, grudge/op.py, test/test_grudge.py
cc @MTCam @inducer
For discussion based on this thread: https://github.com/illinois-ceesd/mirgecom/pull/360#discussion_r638097941
=> Add normals/nodes to dcoll

grudge/op.py, grudge/symbolic/mappers/__init__.py, test/mesh_data.py, test/test_grudge.py
=> Simplify WADG mass inverse

.github/workflows/ci.yml, .gitlab-ci.yml, .test-conda-env-py3.yml
Gitlab sister CI: https://gitlab.tiker.net/inducer/grudge/-/merge_requests/new?merge_request%5Bsource_branch%5D=ompi-from-conda
cc @thomasgibson
=> Github CI: Use OpenMPI from Conda

examples/advection/surface.py, examples/wave/wave-op-var-velocity.py, grudge/discretization.py, test/test_modal_connections.py
https://github.com/inducer/meshmode/pull/225
=> Track warp-and-blend el group split in meshmode

examples/advection/surface.py, examples/advection/var-velocity.py, examples/advection/weak.py, examples/maxwell/cavities.py
=> Fix norm logging in advection, Maxwell examples for device scalars

grudge/trace_pair.py, test/test_trace_pair.py
=> Fix diff property, ugh.

grudge/op.py, grudge/reductions.py
This came about as part of my review of #154. Rather than clumsily describe what I figured should happen, I thought I'd just make these changes. @thomasgibson If you agree with these changes, then #154 (which this targets) with this merged in is good to go from my end.
=> More shared code in array container support

grudge/geometry/metrics.py
Fixes #153 by computing 1-D metric using numpy. The results are always cached.
=> Numpify 1-d metric computations

.github/workflows/ci.yml, examples/wave/wave-op-mpi.py, grudge/array_context.py, grudge/geometry/metrics.py, test/test_grudge.py, test/test_metrics.py
Replaces #208, #207, #203, and #194 and fixes #174
=> Fix metric computation for affine + overintegrated

.github/workflows/ci.yml
Potentially address #211.
cc @thomasgibson
=> Don't run mirgecom downstream CI in parallel

.github/workflows/ci.yml, doc/index.rst, doc/models.rst, examples/advection/var-velocity.py, examples/advection/weak.py, examples/euler/acoustic_pulse.py, examples/euler/vortex.py, examples/maxwell/cavities.py, examples/wave/var-propagation-speed.py, examples/wave/wave-min-mpi.py, examples/wave/wave-op-mpi.py, examples/wave/wave-op-var-velocity.py, grudge/models/euler.py, grudge/shortcuts.py, test/test_euler_model.py
This PR adds a simple Euler model using a nodal DG discretization. This operator is the basis for the corresponding ESDG Euler operator in the entropy stable development branches and will be updated in a future PR related to flux differencing.
=> Add an Euler model

examples/wave/wave-op-mpi.py, grudge/array_context.py
=> Simplify distributed-lazy array context usage

grudge/reductions.py
=> Fix array container support in nodal_sum

.github/workflows/ci.yml
=> Explain --oversubscribe in CI config

grudge/array_context.py
- add documentation
- add logging
- check for correct loopy branch
=> get_reasonable_array_context_class improvements

grudge/discretization.py
Moved in inducer/meshmode#305.
=> Fix sphinx link to ElementGroupFactory

grudge/array_context.py
Needs https://github.com/inducer/pytato/pull/280
=> pass allocator to execute_distributed_partition

grudge/dt_utils.py, grudge/reductions.py, test/test_grudge_sym_old.py
x-ref: https://github.com/inducer/grudge/pull/247#discussion_r843447075
=> Re-bump a tolerance in test_mass_mat_trig (old symbolic tests)

test/test_grudge_sym_old.py
Fixes https://github.com/inducer/grudge/pull/248/
=> Bump the right tolerance (not the wrong one) in test_mass_mat_trig

test/test_grudge_sym_old.py
As requested by @matthiasdiener in
https://github.com/inducer/grudge/pull/249#pullrequestreview-933685048
=> Re-bump tolerance in test_mass_mat_trig (old sym)

grudge/models/euler.py, grudge/op.py, grudge/trace_pair.py
This came out of reviewing https://github.com/illinois-ceesd/mirgecom/pull/581.
@MTCam Could you take a look?
=> Add `project_tracepair`, `tracepair_with_discr_tag`

grudge/op.py, grudge/tools.py, test/test_tools.py
A step towards illinois-ceesd/mirgecom#618.
=> Generalize div/grad helpers so that logic can be reused

grudge/reductions.py, test/test_reductions.py
~~:warning: Depends on inducer/meshmode#330. :warning:~~ (Merged.)
=> Make nodal reductions work with empty meshes

grudge/dof_desc.py, grudge/dt_utils.py, grudge/geometry/metrics.py
Analogous to https://github.com/inducer/meshmode/pull/337, adds `NameHint` tags for a few things in `metrics` and `dt_utils`, and adds a utility to make `DOFDesc` easy to incorporate into `NameHint`s.
=> Add name hints

grudge/array_context.py
=> Do not assume that the callable would be named

grudge/array_context.py
=> disable pylint warning

grudge/array_context.py
=> Import pytato distributed functionality from pytato top-level

grudge/array_context.py
https://github.com/inducer/pytato/pull/393 changes the function signature. Not sure if this is the best way to do it, but it appears to work.
=> Support new find_distributed_partition

grudge/array_context.py, setup.py
Alternative to #321.
cc @matthiasdiener
=> Replace `pyrsistent.pmap` with `immutabledict`

grudge/trace_pair.py, test/test_reductions.py
=> minor cleanups

grudge/geometry/metrics.py
=> Remove `DD_VOLUME_ALL` usage in metrics

test/mesh_data.py, test/test_dt_utils.py, test/test_grudge.py, test/test_reductions.py
Also, refactor test MeshBuilder to not pretend to act as source of truth on mesh order.
=> Add `MeshBuilder.Gmsh{2,3}DMeshBuilder`

.github/workflows/ci.yml, .gitlab-ci.yml
Should address failures like https://gitlab.tiker.net/inducer/grudge/-/jobs/720682.
=> Remove version restriction in sphinx due to now-fixed issue

grudge/dof_desc.py
Doesn't appear to be needed anymore.
=> Remove `DOFDesc.with_dtag`

examples/advection/surface.py, examples/advection/var-velocity.py, examples/advection/weak.py, examples/euler/acoustic_pulse.py, examples/euler/vortex.py, examples/geometry.py, examples/maxwell/cavities.py, examples/wave/var-propagation-speed.py, examples/wave/wave-min-mpi.py, examples/wave/wave-op-mpi.py, examples/wave/wave-op-var-velocity.py, grudge/array_context.py, grudge/models/em.py, grudge/models/euler.py, grudge/trace_pair.py, test/test_mpi_communication.py, test/test_reductions.py
Mostly around `force_device_scalars` and `dataclass_array_container` changes. The remaining warnings are on the pytato side (with too many arguments and unevaluated arguments).
=> Fix some deprecations

grudge/trace_pair.py
- Remove `_TagKeyBuilder` (`KeyBuilder` can handle class types directly now)
- Simplify `base_tag` handling
- Add reference to #223
=> simplify _sym_tag_to_num_tag
